---
- name: Setup GitLab and Runner from Detailed Compose Template
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: Create base directory for GitLab
      ansible.builtin.file:
        path: "{{ gitlab_base_dir }}"
        state: directory
        mode: '0755'
      tags:
        - fs_setup

    - name: Create certs directory for runner
      ansible.builtin.file:
        path: "{{ gitlab_base_dir }}/certs"
        state: directory
        mode: '0755'
      tags:
        - fs_setup

    - name: Generate docker-compose.yml from the definitive template
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: "{{ gitlab_base_dir }}/docker-compose.yml"
        mode: '0644'
      tags:
        - config_gen

    - name: Start GitLab and Runner services using docker-compose
      community.docker.docker_compose:
        project_src: "{{ gitlab_base_dir }}"
        state: present
      tags:
        - service
